name: Deploy to EC2
on:
  push:
    branches:
      - main  # デプロイを実行するブランチ
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd api
          ./mvnw clean package -DskipTests

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "api/target/api-0.0.1-SNAPSHOT.jar"
          target: "~/api"

      - name: SSH and Restart App
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Stopping old app..."
            PID=$(pgrep -f 'api-0.0.1-SNAPSHOT.jar') && kill $PID || true
            echo "Setting environment variables..."
            export DB_URL=${{ secrets.DB_URL }}
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            echo "Launching app..."
            nohup java -jar ~/api/api-0.0.1-SNAPSHOT.jar > ~/api/app.log 2>&1 & disown
            sleep 5
            echo "Checking app status..."
            pgrep -f 'api-0.0.1-SNAPSHOT.jar' && echo "App is running" || echo "App failed to start"
          command_timeout: 10m