name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR file
        run: mvn clean package -DskipTests
        working-directory: ./api

      - name: Build JAR file
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "target/api-0.0.1-SNAPSHOT.jar"
          target: "~/api"

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Killing existing app process if it exists..."
            PID=$(pgrep -f 'api-0.0.1-SNAPSHOT.jar') && kill $PID || echo "No process found"

            echo "Navigating to app directory..."
            cd ~/api

            echo "Launching new app..."
            DB_URL='${{ secrets.DB_URL }}' \
            DB_USERNAME='${{ secrets.DB_USERNAME }}' \
            DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            setsid nohup java -jar api-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &

            echo "App deployment finished."