name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Stopping old app..."
            PID=$(pgrep -f 'api-0.0.1-SNAPSHOT.jar') && kill $PID || true

            echo "Launching app with environment variables via -D options..."
            setsid nohup java \
              -DDB_URL=${{ secrets.DB_URL }} \
              -DDB_USERNAME=${{ secrets.DB_USERNAME }} \
              -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -jar ~/api/api-0.0.1-SNAPSHOT.jar > ~/api/app.log 2>&1 < /dev/null &

            echo "Deployment script finished. App should be launching in the background."